name: Python Lint and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkout the repository
    - name: Set up Python 3.8
      uses: actions/setup-python@v1  # Prebuilt action that sets up python on the container
      with:
        python-version: 3.8
    - name: Install dependencies  # Update PIP then install the needed packages
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install -U pytest
    - name: Lint code  # Can also use `black --check .` to test linting, but not apply it
      run: black .
    - name: Commit linted version
      # Checks if any changes have been made by the linter
      # If so, commits them and pushes to the repo
      # By default won't retrigger a workflow
      run: |
        if ! git diff-index --quiet HEAD --; then
          git config --global user.email "black.linting@example.com"
          git config --global user.name "Black Linting"
          git commit -am "Linted code"
          git push
        fi
    - name: Run tests
      run: pytest